### Description

This notebook was used to load and prepare the recorded Gyro-Data send by the App. In this notebook also a simple NN was created to build a classifiert.

In [5]:
from keras.models import Sequential
from keras.layers import Dense, Activation, Dropout
import numpy as np
import pandas as pd
from keras.utils import plot_model



Using TensorFlow backend.


In [2]:
moving = pd.read_csv("Server/TestData2/TestDatalabeled/walking.csv")

In [3]:
staying = pd.read_csv("Server/TestData2/TestDatalabeled/staying.csv")

In [4]:
sitting = pd.read_csv("Server/TestData2/TestDatalabeled/sitting.csv")

In [5]:
all_movement = pd.concat([moving,staying,sitting])

In [6]:
all_movement = all_movement.sample(frac=1).reset_index(drop=True)


In [7]:
all_movement = all_movement.drop('Unnamed: 0', axis=1)

In [8]:
all_movement.shape

(13842, 21)

In [9]:
train_data = all_movement[0:10000]

In [13]:
train_data.to_csv("Server/TestData2/TestDatalabeled/train.csv")

In [14]:
test_data = all_movement[10001:]

In [15]:
test_data.to_csv("Server/TestData2/TestDatalabeled/test.csv")

Konkrete Trainingsdaten

In [16]:
x_train = train_data[train_data.columns[0:20]].values

In [17]:
y_train = train_data[train_data.columns[20]].values

In [18]:
x_train.shape

(10000, 20)

In [19]:
x_test = test_data[test_data.columns[0:20]].values

In [20]:
x_test.shape


(3841, 20)

In [21]:
y_test = test_data[test_data.columns[20]].values

In [22]:
y_test_f = np.zeros(shape=(y_test.shape[0], 3))

In [23]:
for item in range(0, y_test.shape[0]):
    y_test_f[item][int(y_test[item])-1] = 0.99
    print(y_test_f[item])
    print(y_test[item])

[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0

[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0

[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0

2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.  

[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0

[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0

1
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.  

In [24]:
y_train_f = np.zeros(shape=(y_train.shape[0], 3))

In [25]:
for item in range(0, y_train.shape[0]):
    y_train_f[item][int(y_train[item])-1] = 0.99
    print(y_train_f[item])
    print(y_train[item])

[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0

2
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.  

[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0

[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.   0

2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.  

3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.  

[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0

[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0

3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.  

3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.  

[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.99 0

[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.99 0

3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.  

3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.  

[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0

[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0

3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.  

3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.  

[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0

[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0

In [26]:
model = Sequential()
model.add(Dense(20, activation='relu', input_dim=(20)))
model.add(Dropout(0.2))
model.add(Dense(30, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(20, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(3, activation='softmax'))

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])


In [27]:
model.fit(x_train, y_train_f, epochs=700, batch_size=100)

Epoch 1/700
10000/10000 [==============================] - 1s 100us/step - loss: 1.4046 - acc: 0.4783
Epoch 2/700
10000/10000 [==============================] - 0s 23us/step - loss: 0.7314 - acc: 0.6386
Epoch 3/700
10000/10000 [==============================] - 0s 23us/step - loss: 0.6410 - acc: 0.6880
Epoch 4/700
10000/10000 [==============================] - 0s 22us/step - loss: 0.5707 - acc: 0.7248
Epoch 5/700
10000/10000 [==============================] - 0s 22us/step - loss: 0.5348 - acc: 0.7454
Epoch 6/700
10000/10000 [==============================] - 0s 22us/step - loss: 0.4955 - acc: 0.7679
Epoch 7/700
10000/10000 [==============================] - 0s 21us/step - loss: 0.4795 - acc: 0.7796
Epoch 8/700
10000/10000 [==============================] - 0s 21us/step - loss: 0.4540 - acc: 0.7879
Epoch 9/700
10000/10000 [==============================] - 0s 20us/step - loss: 0.4386 - acc: 0.7924
Epoch 10/700
10000/10000 [==============================] - 0s 23us/step - loss: 0.4240 - 

10000/10000 [==============================] - 0s 20us/step - loss: 0.2027 - acc: 0.8832
Epoch 160/700
10000/10000 [==============================] - 0s 21us/step - loss: 0.2007 - acc: 0.8837
Epoch 161/700
10000/10000 [==============================] - 0s 19us/step - loss: 0.2031 - acc: 0.8837
Epoch 162/700
10000/10000 [==============================] - 0s 22us/step - loss: 0.2031 - acc: 0.8832
Epoch 163/700
10000/10000 [==============================] - 0s 21us/step - loss: 0.2061 - acc: 0.8812
Epoch 164/700
10000/10000 [==============================] - 0s 19us/step - loss: 0.2045 - acc: 0.8878
Epoch 165/700
10000/10000 [==============================] - 0s 22us/step - loss: 0.2045 - acc: 0.8842
Epoch 166/700
10000/10000 [==============================] - 0s 20us/step - loss: 0.1979 - acc: 0.8859
Epoch 167/700
10000/10000 [==============================] - 0s 19us/step - loss: 0.2075 - acc: 0.8806
Epoch 168/700
10000/10000 [==============================] - 0s 22us/step - loss: 0.203

10000/10000 [==============================] - 0s 37us/step - loss: 0.1887 - acc: 0.8884
Epoch 318/700
10000/10000 [==============================] - 0s 35us/step - loss: 0.1844 - acc: 0.8912
Epoch 319/700
10000/10000 [==============================] - 0s 29us/step - loss: 0.1898 - acc: 0.8870
Epoch 320/700
10000/10000 [==============================] - 0s 28us/step - loss: 0.1922 - acc: 0.8863
Epoch 321/700
10000/10000 [==============================] - 0s 24us/step - loss: 0.1928 - acc: 0.8872
Epoch 322/700
10000/10000 [==============================] - 0s 23us/step - loss: 0.1930 - acc: 0.8849
Epoch 323/700
10000/10000 [==============================] - 0s 24us/step - loss: 0.1885 - acc: 0.8848
Epoch 324/700
10000/10000 [==============================] - 0s 28us/step - loss: 0.1918 - acc: 0.8883
Epoch 325/700
10000/10000 [==============================] - 0s 28us/step - loss: 0.1959 - acc: 0.8859
Epoch 326/700
10000/10000 [==============================] - 0s 29us/step - loss: 0.192

10000/10000 [==============================] - 0s 21us/step - loss: 0.1929 - acc: 0.8872
Epoch 476/700
10000/10000 [==============================] - 0s 20us/step - loss: 0.1881 - acc: 0.8924
Epoch 477/700
10000/10000 [==============================] - 0s 20us/step - loss: 0.1833 - acc: 0.8900
Epoch 478/700
10000/10000 [==============================] - 0s 22us/step - loss: 0.1891 - acc: 0.8888
Epoch 479/700
10000/10000 [==============================] - 0s 19us/step - loss: 0.1903 - acc: 0.8866
Epoch 480/700
10000/10000 [==============================] - 0s 20us/step - loss: 0.1946 - acc: 0.8860
Epoch 481/700
10000/10000 [==============================] - 0s 23us/step - loss: 0.1927 - acc: 0.8900
Epoch 482/700
10000/10000 [==============================] - 0s 23us/step - loss: 0.1891 - acc: 0.8909
Epoch 483/700
10000/10000 [==============================] - 0s 23us/step - loss: 0.2026 - acc: 0.8825
Epoch 484/700
10000/10000 [==============================] - 0s 22us/step - loss: 0.203

10000/10000 [==============================] - 0s 26us/step - loss: 0.1844 - acc: 0.8874
Epoch 633/700
10000/10000 [==============================] - 0s 27us/step - loss: 0.1860 - acc: 0.8897
Epoch 634/700
10000/10000 [==============================] - 0s 27us/step - loss: 0.1866 - acc: 0.8917
Epoch 635/700
10000/10000 [==============================] - 0s 28us/step - loss: 0.1921 - acc: 0.8879
Epoch 636/700
10000/10000 [==============================] - 0s 26us/step - loss: 0.1964 - acc: 0.8917
Epoch 637/700
10000/10000 [==============================] - 0s 25us/step - loss: 0.1810 - acc: 0.8944
Epoch 638/700
10000/10000 [==============================] - 0s 25us/step - loss: 0.1864 - acc: 0.8904
Epoch 639/700
10000/10000 [==============================] - 0s 28us/step - loss: 0.1900 - acc: 0.8873
Epoch 640/700
10000/10000 [==============================] - 0s 26us/step - loss: 0.1895 - acc: 0.8907
Epoch 641/700
10000/10000 [==============================] - 0s 33us/step - loss: 0.192

In [28]:
score = model.evaluate(x_test, y_test_f, batch_size=128)

3841/3841 [==============================] - 0s 45us/step


In [29]:
score

[0.1569945371434077, 0.899244988284301]

In [1]:
model.save("moreData.h5")

NameError: name 'model' is not defined

In [3]:
from keras.models import load_model
from keras.utils import plot_model

model_l = load_model("moreData.h5")