In [1]:
from keras.models import Sequential
from keras.layers import Dense, Activation, Dropout
import numpy as np
import pandas as pd


Using TensorFlow backend.


In [2]:
moving = pd.read_csv("Server/TestData2/TestDatalabeled/walking.csv")

In [3]:
staying = pd.read_csv("Server/TestData2/TestDatalabeled/staying.csv")

In [4]:
sitting = pd.read_csv("Server/TestData2/TestDatalabeled/sitting.csv")

In [5]:
all_movement = pd.concat([moving,staying,sitting])

In [6]:
all_movement = all_movement.sample(frac=1).reset_index(drop=True)


In [7]:
all_movement = all_movement.drop('Unnamed: 0', axis=1)

In [8]:
all_movement.shape

(13842, 21)

In [9]:
train_data = all_movement[0:10000]

In [10]:
train_data.to_csv("Server/TestData2/TestDatalabeled/train.csv")

In [11]:
test_data = all_movement[10001:]

In [12]:
test_data.to_csv("Server/TestData2/TestDatalabeled/test.csv")

Konkrete Trainingsdaten

In [13]:
x_train = train_data[train_data.columns[0:20]].values

In [14]:
y_train = train_data[train_data.columns[20]].values

In [15]:
x_train.shape

(10000, 20)

In [16]:
x_test = test_data[test_data.columns[0:20]].values

In [17]:
x_test.shape


(3841, 20)

In [18]:
y_test = test_data[test_data.columns[20]].values

In [19]:
y_test_f = np.zeros(shape=(y_test.shape[0], 3))

In [20]:
for item in range(0, y_test.shape[0]):
    y_test_f[item][int(y_test[item])-1] = 0.99
    print(y_test_f[item])
    print(y_test[item])

[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0

[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0

[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.99 0.   0

2
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99

3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.  

[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.99 0

[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0

3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.  

In [21]:
y_train_f = np.zeros(shape=(y_train.shape[0], 3))

In [22]:
for item in range(0, y_train.shape[0]):
    y_train_f[item][int(y_train[item])-1] = 0.99
    print(y_train_f[item])
    print(y_train[item])

[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0

1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99

1
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.  

[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0

1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.99

1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.  

[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0

[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0

1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99

1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.99 0.  

[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.   0

[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0

3
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.  

1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.  

[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0

[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0

1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.  

2
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.  

[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.   0.99]
3
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.   0.99]
3
[0.99 0.   0.  ]
1
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.   0.99 0.  ]
2
[0.99 0.   0.  ]
1
[0.   0.   0

In [23]:
model = Sequential()
model.add(Dense(20, activation='relu', input_dim=(20)))
model.add(Dropout(0.2))
model.add(Dense(30, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(20, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(3, activation='softmax'))

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])


In [24]:
model.fit(x_train, y_train_f, epochs=700, batch_size=100)

Epoch 1/700
10000/10000 [==============================] - 1s 79us/step - loss: 1.1144 - acc: 0.5365
Epoch 2/700
10000/10000 [==============================] - 0s 17us/step - loss: 0.7379 - acc: 0.6462
Epoch 3/700
10000/10000 [==============================] - 0s 14us/step - loss: 0.6561 - acc: 0.6909
Epoch 4/700
10000/10000 [==============================] - 0s 16us/step - loss: 0.5889 - acc: 0.7268
Epoch 5/700
10000/10000 [==============================] - 0s 15us/step - loss: 0.5495 - acc: 0.7542
Epoch 6/700
10000/10000 [==============================] - 0s 15us/step - loss: 0.5070 - acc: 0.7715
Epoch 7/700
10000/10000 [==============================] - 0s 15us/step - loss: 0.4716 - acc: 0.7777
Epoch 8/700
10000/10000 [==============================] - 0s 14us/step - loss: 0.4387 - acc: 0.8016
Epoch 9/700
10000/10000 [==============================] - 0s 19us/step - loss: 0.4172 - acc: 0.8098
Epoch 10/700
10000/10000 [==============================] - 0s 17us/step - loss: 0.4043 - a

10000/10000 [==============================] - 0s 16us/step - loss: 0.2195 - acc: 0.8844
Epoch 81/700
10000/10000 [==============================] - 0s 14us/step - loss: 0.2149 - acc: 0.8885
Epoch 82/700
10000/10000 [==============================] - 0s 14us/step - loss: 0.2128 - acc: 0.8899
Epoch 83/700
10000/10000 [==============================] - 0s 15us/step - loss: 0.2170 - acc: 0.8796
Epoch 84/700
10000/10000 [==============================] - 0s 17us/step - loss: 0.2112 - acc: 0.8886
Epoch 85/700
10000/10000 [==============================] - 0s 19us/step - loss: 0.2100 - acc: 0.8908
Epoch 86/700
10000/10000 [==============================] - 0s 15us/step - loss: 0.2160 - acc: 0.8886
Epoch 87/700
10000/10000 [==============================] - 0s 16us/step - loss: 0.2125 - acc: 0.8873
Epoch 88/700
10000/10000 [==============================] - 0s 14us/step - loss: 0.2129 - acc: 0.8888: 0s - loss: 0.2118 - acc: 0.889
Epoch 89/700
10000/10000 [==============================] - 0s 

10000/10000 [==============================] - 0s 16us/step - loss: 0.1956 - acc: 0.8919
Epoch 160/700
10000/10000 [==============================] - 0s 14us/step - loss: 0.1913 - acc: 0.8975
Epoch 161/700
10000/10000 [==============================] - 0s 15us/step - loss: 0.1990 - acc: 0.8935
Epoch 162/700
10000/10000 [==============================] - 0s 14us/step - loss: 0.1957 - acc: 0.8935
Epoch 163/700
10000/10000 [==============================] - 0s 16us/step - loss: 0.1956 - acc: 0.8920
Epoch 164/700
10000/10000 [==============================] - 0s 15us/step - loss: 0.2042 - acc: 0.8891
Epoch 165/700
10000/10000 [==============================] - 0s 14us/step - loss: 0.2082 - acc: 0.8880
Epoch 166/700
10000/10000 [==============================] - 0s 15us/step - loss: 0.2068 - acc: 0.8893
Epoch 167/700
10000/10000 [==============================] - 0s 15us/step - loss: 0.2054 - acc: 0.8882
Epoch 168/700
10000/10000 [==============================] - 0s 15us/step - loss: 0.209

10000/10000 [==============================] - 0s 12us/step - loss: 0.1919 - acc: 0.8937
Epoch 239/700
10000/10000 [==============================] - 0s 15us/step - loss: 0.1891 - acc: 0.8960
Epoch 240/700
10000/10000 [==============================] - 0s 15us/step - loss: 0.1882 - acc: 0.8981
Epoch 241/700
10000/10000 [==============================] - 0s 19us/step - loss: 0.1884 - acc: 0.8942
Epoch 242/700
10000/10000 [==============================] - 0s 16us/step - loss: 0.1861 - acc: 0.8960
Epoch 243/700
10000/10000 [==============================] - 0s 11us/step - loss: 0.1975 - acc: 0.8920
Epoch 244/700
10000/10000 [==============================] - 0s 14us/step - loss: 0.1959 - acc: 0.8908
Epoch 245/700
10000/10000 [==============================] - 0s 17us/step - loss: 0.1899 - acc: 0.8978
Epoch 246/700
10000/10000 [==============================] - 0s 15us/step - loss: 0.1930 - acc: 0.8935
Epoch 247/700
10000/10000 [==============================] - 0s 14us/step - loss: 0.195

10000/10000 [==============================] - 0s 16us/step - loss: 0.1815 - acc: 0.8956
Epoch 318/700
10000/10000 [==============================] - 0s 14us/step - loss: 0.1942 - acc: 0.8944
Epoch 319/700
10000/10000 [==============================] - 0s 14us/step - loss: 0.1850 - acc: 0.8974
Epoch 320/700
10000/10000 [==============================] - 0s 15us/step - loss: 0.1794 - acc: 0.8983
Epoch 321/700
10000/10000 [==============================] - 0s 15us/step - loss: 0.1842 - acc: 0.8955
Epoch 322/700
10000/10000 [==============================] - 0s 14us/step - loss: 0.1920 - acc: 0.8959
Epoch 323/700
10000/10000 [==============================] - 0s 12us/step - loss: 0.1877 - acc: 0.8961
Epoch 324/700
10000/10000 [==============================] - 0s 14us/step - loss: 0.1808 - acc: 0.8971
Epoch 325/700
10000/10000 [==============================] - 0s 12us/step - loss: 0.1798 - acc: 0.8968
Epoch 326/700
10000/10000 [==============================] - 0s 16us/step - loss: 0.178

10000/10000 [==============================] - 0s 18us/step - loss: 0.1855 - acc: 0.8986
Epoch 397/700
10000/10000 [==============================] - 0s 22us/step - loss: 0.1869 - acc: 0.8970
Epoch 398/700
10000/10000 [==============================] - 0s 18us/step - loss: 0.1834 - acc: 0.9006
Epoch 399/700
10000/10000 [==============================] - 0s 15us/step - loss: 0.1907 - acc: 0.8954
Epoch 400/700
10000/10000 [==============================] - 0s 17us/step - loss: 0.1839 - acc: 0.9009
Epoch 401/700
10000/10000 [==============================] - 0s 17us/step - loss: 0.1887 - acc: 0.8935
Epoch 402/700
10000/10000 [==============================] - 0s 17us/step - loss: 0.1826 - acc: 0.9006
Epoch 403/700
10000/10000 [==============================] - 0s 14us/step - loss: 0.1843 - acc: 0.8937
Epoch 404/700
10000/10000 [==============================] - 0s 13us/step - loss: 0.1827 - acc: 0.8986
Epoch 405/700
10000/10000 [==============================] - 0s 19us/step - loss: 0.178

10000/10000 [==============================] - 0s 16us/step - loss: 0.1846 - acc: 0.8978
Epoch 476/700
10000/10000 [==============================] - 0s 16us/step - loss: 0.1771 - acc: 0.9006
Epoch 477/700
10000/10000 [==============================] - 0s 14us/step - loss: 0.1856 - acc: 0.8962
Epoch 478/700
10000/10000 [==============================] - 0s 15us/step - loss: 0.1840 - acc: 0.8966
Epoch 479/700
10000/10000 [==============================] - 0s 18us/step - loss: 0.1869 - acc: 0.8942
Epoch 480/700
10000/10000 [==============================] - 0s 19us/step - loss: 0.1830 - acc: 0.8976
Epoch 481/700
10000/10000 [==============================] - 0s 17us/step - loss: 0.1862 - acc: 0.8975
Epoch 482/700
10000/10000 [==============================] - 0s 17us/step - loss: 0.1784 - acc: 0.9019
Epoch 483/700
10000/10000 [==============================] - 0s 18us/step - loss: 0.1930 - acc: 0.8961
Epoch 484/700
10000/10000 [==============================] - 0s 14us/step - loss: 0.185

10000/10000 [==============================] - 0s 14us/step - loss: 0.1924 - acc: 0.8922
Epoch 555/700
10000/10000 [==============================] - 0s 17us/step - loss: 0.1821 - acc: 0.8969
Epoch 556/700
10000/10000 [==============================] - 0s 16us/step - loss: 0.1901 - acc: 0.8994
Epoch 557/700
10000/10000 [==============================] - 0s 14us/step - loss: 0.1844 - acc: 0.8958
Epoch 558/700
10000/10000 [==============================] - 0s 16us/step - loss: 0.1754 - acc: 0.8978
Epoch 559/700
10000/10000 [==============================] - 0s 16us/step - loss: 0.1881 - acc: 0.8908
Epoch 560/700
10000/10000 [==============================] - 0s 18us/step - loss: 0.1850 - acc: 0.8960
Epoch 561/700
10000/10000 [==============================] - 0s 21us/step - loss: 0.1814 - acc: 0.8977
Epoch 562/700
10000/10000 [==============================] - 0s 19us/step - loss: 0.1763 - acc: 0.9007
Epoch 563/700
10000/10000 [==============================] - 0s 17us/step - loss: 0.181

10000/10000 [==============================] - 0s 12us/step - loss: 0.1782 - acc: 0.8988
Epoch 634/700
10000/10000 [==============================] - 0s 12us/step - loss: 0.1849 - acc: 0.8984
Epoch 635/700
10000/10000 [==============================] - 0s 12us/step - loss: 0.1831 - acc: 0.8978
Epoch 636/700
10000/10000 [==============================] - 0s 14us/step - loss: 0.1827 - acc: 0.9009
Epoch 637/700
10000/10000 [==============================] - 0s 15us/step - loss: 0.1763 - acc: 0.8998
Epoch 638/700
10000/10000 [==============================] - 0s 14us/step - loss: 0.1785 - acc: 0.9044
Epoch 639/700
10000/10000 [==============================] - 0s 14us/step - loss: 0.1762 - acc: 0.8983
Epoch 640/700
10000/10000 [==============================] - 0s 13us/step - loss: 0.1824 - acc: 0.8987
Epoch 641/700
10000/10000 [==============================] - 0s 14us/step - loss: 0.1718 - acc: 0.9013
Epoch 642/700
10000/10000 [==============================] - 0s 12us/step - loss: 0.181

In [25]:
score = model.evaluate(x_test, y_test_f, batch_size=128)

3841/3841 [==============================] - 0s 39us/step


In [26]:
score

[0.23741851193819216, 0.8747721947409529]

In [27]:
model.save("moreData.h5")