In [1]:
from keras.models import Sequential
from keras.layers import Dense, Activation, Dropout
import numpy as np
import pandas as pd


Using TensorFlow backend.


https://keras.io/getting-started/sequential-model-guide/ 

## Shuffeln um bessere Ergebnisse zu erzielen

In [2]:
tidy = pd.read_csv('tidy_dataset.csv')

In [3]:
tidy = tidy.sample(frac=1).reset_index(drop=True)

In [4]:
tidy.shape

(10299, 35)

In [5]:
tidy.head()

tbodyaccmeanx  tbodyaccmeany  tbodyaccmeanz  tgravityaccmeanx  \
0       0.165140      -0.043492      -0.074064          0.848306   
1       0.321384      -0.016800      -0.007188          0.785586   
2       0.375202      -0.036118      -0.167107          0.935616   
3       0.274096      -0.001147      -0.100892          0.931490   
4       0.284224       0.001572      -0.099114          0.964880   

   tgravityaccmeany  tgravityaccmeanz  tbodyaccjerkmeanx  tbodyaccjerkmeany  \
0         -0.364315         -0.199395           0.123766          -0.302659   
1         -0.257828         -0.436371          -0.032949           0.573375   
2         -0.240172          0.004431          -0.154462          -0.018515   
3          0.005872          0.262719           0.080295           0.022722   
4         -0.147883         -0.019395           0.855403          -0.094337   

   tbodyaccjerkmeanz  tbodygyromeanx         ...          fbodyaccjerkmeanz  \
0          -0.126364       -0.460555         ...                  -0.473364   
1           0.564844       -0.505539         ...                   0.329480   
2          -0.182814        0.007892         ...                  -0.637117   
3           0.010795       -0.028466         ...                  -0.979524   
4          -0.146432        0.014339         ...                  -0.669475   

   fbodygyromeanx  fbodygyromeany  fbodygyromeanz  fbodyaccmagmean  \
0       -0.458124       -0.413475       -0.227673        -0.036231   
1       -0.108887        0.274285        0.643878         0.873943   
2       -0.328849       -0.623572       -0.400084        -0.203084   
3       -0.983080       -0.984302       -0.962203        -0.964124   
4       -0.430840       -0.409366       -0.532773        -0.049840   

   fbodybodyaccjerkmagmean  fbodybodygyromagmean  fbodybodygyrojerkmagmean  \
0                 0.034579             -0.412982                 -0.629408   
1                 0.556822              0.214290                  0.000503   
2                -0.365616             -0.552269                 -0.675565   
3                -0.978781             -0.981834                 -0.992614   
4                -0.019962             -0.443357                 -0.499902   

   subject            activity  
0       22    WALKING_UPSTAIRS  
1       14  WALKING_DOWNSTAIRS  
2       26    WALKING_UPSTAIRS  
3       30             SITTING  
4       12             WALKING  

[5 rows x 35 columns]

In [6]:
labelsDict = {
    'WALKING': 1,
    'WALKING_UPSTAIRS': 2,
    'WALKING_DOWNSTAIRS': 3,
    'SITTING': 4,
    'STANDING': 5,
    'LAYING': 6
}

In [7]:
tidy.to_csv(path_or_buf="tidy_dataset_all.csv")

In [8]:
df = pd.read_csv('tidy_dataset_training.csv')

In [9]:
df.head()

Unnamed: 0  tbodyaccmeanx  tbodyaccmeany  tbodyaccmeanz  tgravityaccmeanx  \
0           0       0.329943       0.017637       0.011913          0.831881   
1           1       0.331972      -0.007308      -0.110539          0.961025   
2           2       0.295423       0.003096      -0.127563          0.917727   
3           3       0.393122      -0.007415      -0.012344          0.944091   
4           4       0.319131      -0.008362      -0.113999          0.947141   

   tgravityaccmeany  tgravityaccmeanz  tbodyaccjerkmeanx  tbodyaccjerkmeany  \
0         -0.439108         -0.154553          -0.158938           0.133241   
1          0.056595          0.058772          -0.238494          -0.120963   
2         -0.305044         -0.106862           0.042129           0.036150   
3         -0.113783          0.108030          -0.011614          -0.163172   
4         -0.219883         -0.146451           0.260639          -0.167597   

   tbodyaccjerkmeanz    ...     fbodyaccjerkmeanz  fbodygyromeanx  \
0           0.027831    ...             -0.576268        0.021158   
1          -0.113624    ...             -0.390560       -0.327703   
2           0.140766    ...             -0.508754       -0.380509   
3          -0.243706    ...             -0.767078       -0.301157   
4          -0.197442    ...             -0.671305       -0.583020   

   fbodygyromeany  fbodygyromeanz  fbodyaccmagmean  fbodybodyaccjerkmagmean  \
0       -0.286196       -0.068256        -0.016640                -0.202842   
1       -0.301334       -0.110165        -0.037761                 0.108808   
2       -0.208828       -0.280720        -0.218158                -0.193487   
3       -0.676213       -0.486247        -0.425524                -0.563987   
4       -0.668782       -0.554829        -0.453847                -0.535373   

   fbodybodygyromagmean  fbodybodygyrojerkmagmean  subject  activity  
0             -0.308473                 -0.554294       19         2  
1             -0.333391                 -0.550982       10         1  
2             -0.209536                 -0.366694        1         1  
3             -0.479884                 -0.729436       25         3  
4             -0.698936                 -0.810464       27         2  

[5 rows x 36 columns]

Input shape ist (rows, columns)

In [12]:
df.columns[20]

'tbodygyrojerkmagmean'

In [22]:
x_train = df[df.columns[1:21]].values

In [23]:
x_train.shape

(10001, 20)

In [24]:
x_train[0][19]

-0.45618473999999998

In [25]:
y_train_preset = df[df.columns[35]].values

In [26]:
y_train_preset

array([2, 1, 1, ..., 4, 4, 3], dtype=int64)

In [27]:
y_train_final = np.zeros(shape=(y_train_preset.shape[0] ,6))

In [28]:
y_train_final[1]

array([ 0.,  0.,  0.,  0.,  0.,  0.])

In [29]:
for item in range(0, y_train_preset.shape[0]):
    y_train_final[item][int(y_train_preset[item])-1] = 0.99
    print(y_train_final[item])
    print(y_train_preset[item])

[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.    0.99]
6


[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.99  0.    0.  ]
4


[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.99  0.  ]
5


[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.99  0.  ]
5


[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.99  0.    0.  ]
4


3
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.99  0.    0.    0.    0.  ]


[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.99  0.    0.  ]
4


[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.    0.99]
6


[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.99  0.    0.    0.    0.  ]
2


1
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.99  0.    0.    0.    0.    0.  ]


[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.99  0.    0.  ]
4


[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.99  0.  ]
5


[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.99  0.    0.    0.    0.    0.  ]
1


6
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.99  0.    0.  ]


5
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.99  0.  ]


[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.99  0.    0.  ]
4


[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.99  0.    0.    0.    0.    0.  ]
1


6
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.99  0.    0.    0.  ]


[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.99  0.    0.  ]
4


[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.99  0.    0.  ]
4


2
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.99  0.    0.  ]


1
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.    0.99]


[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.    0.99]
6


[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.99  0.    0.    0.  ]
3


[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.99  0.    0.    0.    0.    0.  ]
1


2
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.99  0.  ]


[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.99  0.    0.    0.  ]
3


### Test Data

### Netz programmieren
Input ist jetzt vorbereitet

In [34]:
model = Sequential()
model.add(Dense(20, activation='relu', input_dim=(20)))
model.add(Dropout(0.2))
model.add(Dense(20, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(6, activation='softmax'))

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])



In [36]:
model.fit(x_train, y_train_final, epochs=1000, batch_size=200)

Epoch 1/1000
10001/10001 [==============================] - 0s 14us/step - loss: 0.2470 - acc: 0.9021
Epoch 2/1000
10001/10001 [==============================] - 0s 13us/step - loss: 0.2522 - acc: 0.9007
Epoch 3/1000
10001/10001 [==============================] - 0s 12us/step - loss: 0.2465 - acc: 0.9009
Epoch 4/1000
10001/10001 [==============================] - 0s 13us/step - loss: 0.2473 - acc: 0.9004
Epoch 5/1000
10001/10001 [==============================] - 0s 13us/step - loss: 0.2522 - acc: 0.8969
Epoch 6/1000
10001/10001 [==============================] - 0s 12us/step - loss: 0.2513 - acc: 0.8977
Epoch 7/1000
10001/10001 [==============================] - 0s 13us/step - loss: 0.2509 - acc: 0.8971
Epoch 8/1000
10001/10001 [==============================] - 0s 13us/step - loss: 0.2540 - acc: 0.8960
Epoch 9/1000
10001/10001 [==============================] - 0s 12us/step - loss: 0.2433 - acc: 0.9014
Epoch 10/1000
10001/10001 [==============================] - 0s 12us/step - loss: 

10001/10001 [==============================] - 0s 12us/step - loss: 0.2508 - acc: 0.8974
Epoch 81/1000
10001/10001 [==============================] - 0s 13us/step - loss: 0.2521 - acc: 0.8985
Epoch 82/1000
10001/10001 [==============================] - 0s 10us/step - loss: 0.2478 - acc: 0.9002
Epoch 83/1000
10001/10001 [==============================] - 0s 13us/step - loss: 0.2415 - acc: 0.9028
Epoch 84/1000
10001/10001 [==============================] - 0s 13us/step - loss: 0.2500 - acc: 0.9014
Epoch 85/1000
10001/10001 [==============================] - 0s 12us/step - loss: 0.2545 - acc: 0.8974
Epoch 86/1000
10001/10001 [==============================] - 0s 12us/step - loss: 0.2454 - acc: 0.9012
Epoch 87/1000
10001/10001 [==============================] - 0s 12us/step - loss: 0.2494 - acc: 0.9022
Epoch 88/1000
10001/10001 [==============================] - 0s 12us/step - loss: 0.2531 - acc: 0.8998
Epoch 89/1000
10001/10001 [==============================] - 0s 12us/step - loss: 0.253

10001/10001 [==============================] - 0s 12us/step - loss: 0.2469 - acc: 0.8996
Epoch 159/1000
10001/10001 [==============================] - 0s 13us/step - loss: 0.2480 - acc: 0.9015
Epoch 160/1000
10001/10001 [==============================] - 0s 13us/step - loss: 0.2452 - acc: 0.9008
Epoch 161/1000
10001/10001 [==============================] - 0s 13us/step - loss: 0.2479 - acc: 0.8987
Epoch 162/1000
10001/10001 [==============================] - 0s 14us/step - loss: 0.2505 - acc: 0.8983
Epoch 163/1000
10001/10001 [==============================] - 0s 13us/step - loss: 0.2427 - acc: 0.9020
Epoch 164/1000
10001/10001 [==============================] - 0s 14us/step - loss: 0.2477 - acc: 0.9023
Epoch 165/1000
10001/10001 [==============================] - 0s 14us/step - loss: 0.2467 - acc: 0.9005
Epoch 166/1000
10001/10001 [==============================] - 0s 14us/step - loss: 0.2460 - acc: 0.9011
Epoch 167/1000
10001/10001 [==============================] - 0s 14us/step - lo

10001/10001 [==============================] - 0s 12us/step - loss: 0.2453 - acc: 0.8985
Epoch 237/1000
10001/10001 [==============================] - 0s 12us/step - loss: 0.2476 - acc: 0.9003
Epoch 238/1000
10001/10001 [==============================] - 0s 12us/step - loss: 0.2557 - acc: 0.8929
Epoch 239/1000
10001/10001 [==============================] - 0s 13us/step - loss: 0.2429 - acc: 0.9021
Epoch 240/1000
10001/10001 [==============================] - 0s 12us/step - loss: 0.2438 - acc: 0.8995
Epoch 241/1000
10001/10001 [==============================] - 0s 12us/step - loss: 0.2370 - acc: 0.9039
Epoch 242/1000
10001/10001 [==============================] - 0s 11us/step - loss: 0.2493 - acc: 0.8992
Epoch 243/1000
10001/10001 [==============================] - 0s 10us/step - loss: 0.2486 - acc: 0.8974
Epoch 244/1000
10001/10001 [==============================] - 0s 10us/step - loss: 0.2464 - acc: 0.9031
Epoch 245/1000
10001/10001 [==============================] - 0s 11us/step - lo

10001/10001 [==============================] - 0s 13us/step - loss: 0.2417 - acc: 0.9045
Epoch 315/1000
10001/10001 [==============================] - 0s 14us/step - loss: 0.2589 - acc: 0.8906
Epoch 316/1000
10001/10001 [==============================] - 0s 12us/step - loss: 0.2493 - acc: 0.8943
Epoch 317/1000
10001/10001 [==============================] - 0s 12us/step - loss: 0.2470 - acc: 0.9012
Epoch 318/1000
10001/10001 [==============================] - 0s 13us/step - loss: 0.2583 - acc: 0.8922
Epoch 319/1000
10001/10001 [==============================] - 0s 10us/step - loss: 0.2506 - acc: 0.9000
Epoch 320/1000
10001/10001 [==============================] - 0s 14us/step - loss: 0.2465 - acc: 0.9004
Epoch 321/1000
10001/10001 [==============================] - 0s 11us/step - loss: 0.2461 - acc: 0.8976
Epoch 322/1000
10001/10001 [==============================] - 0s 12us/step - loss: 0.2424 - acc: 0.9033
Epoch 323/1000
10001/10001 [==============================] - 0s 14us/step - lo

10001/10001 [==============================] - 0s 15us/step - loss: 0.2400 - acc: 0.9043
Epoch 393/1000
10001/10001 [==============================] - 0s 18us/step - loss: 0.2443 - acc: 0.9002
Epoch 394/1000
10001/10001 [==============================] - 0s 17us/step - loss: 0.2471 - acc: 0.9008
Epoch 395/1000
10001/10001 [==============================] - 0s 17us/step - loss: 0.2496 - acc: 0.8983
Epoch 396/1000
10001/10001 [==============================] - 0s 16us/step - loss: 0.2421 - acc: 0.9016
Epoch 397/1000
10001/10001 [==============================] - 0s 16us/step - loss: 0.2370 - acc: 0.9039
Epoch 398/1000
10001/10001 [==============================] - 0s 13us/step - loss: 0.2446 - acc: 0.8998
Epoch 399/1000
10001/10001 [==============================] - 0s 13us/step - loss: 0.2541 - acc: 0.8910
Epoch 400/1000
10001/10001 [==============================] - 0s 13us/step - loss: 0.2473 - acc: 0.8991
Epoch 401/1000
10001/10001 [==============================] - 0s 14us/step - lo

10001/10001 [==============================] - 0s 12us/step - loss: 0.2382 - acc: 0.9007
Epoch 471/1000
10001/10001 [==============================] - 0s 13us/step - loss: 0.2365 - acc: 0.9039
Epoch 472/1000
10001/10001 [==============================] - 0s 10us/step - loss: 0.2407 - acc: 0.9038
Epoch 473/1000
10001/10001 [==============================] - 0s 12us/step - loss: 0.2408 - acc: 0.9013
Epoch 474/1000
10001/10001 [==============================] - 0s 13us/step - loss: 0.2431 - acc: 0.9011
Epoch 475/1000
10001/10001 [==============================] - 0s 13us/step - loss: 0.2374 - acc: 0.9015
Epoch 476/1000
10001/10001 [==============================] - 0s 12us/step - loss: 0.2443 - acc: 0.9001
Epoch 477/1000
10001/10001 [==============================] - 0s 13us/step - loss: 0.2483 - acc: 0.8968
Epoch 478/1000
10001/10001 [==============================] - 0s 13us/step - loss: 0.2460 - acc: 0.9005
Epoch 479/1000
10001/10001 [==============================] - 0s 12us/step - lo

10001/10001 [==============================] - 0s 13us/step - loss: 0.2553 - acc: 0.8938
Epoch 549/1000
10001/10001 [==============================] - 0s 12us/step - loss: 0.2475 - acc: 0.8997
Epoch 550/1000
10001/10001 [==============================] - 0s 12us/step - loss: 0.2450 - acc: 0.8992
Epoch 551/1000
10001/10001 [==============================] - 0s 13us/step - loss: 0.2426 - acc: 0.9013
Epoch 552/1000
10001/10001 [==============================] - 0s 11us/step - loss: 0.2422 - acc: 0.9025
Epoch 553/1000
10001/10001 [==============================] - 0s 12us/step - loss: 0.2400 - acc: 0.9021
Epoch 554/1000
10001/10001 [==============================] - 0s 11us/step - loss: 0.2381 - acc: 0.9023
Epoch 555/1000
10001/10001 [==============================] - 0s 13us/step - loss: 0.2405 - acc: 0.9007
Epoch 556/1000
10001/10001 [==============================] - 0s 13us/step - loss: 0.2437 - acc: 0.9006
Epoch 557/1000
10001/10001 [==============================] - 0s 12us/step - lo

10001/10001 [==============================] - 0s 13us/step - loss: 0.2637 - acc: 0.8946
Epoch 627/1000
10001/10001 [==============================] - 0s 14us/step - loss: 0.2522 - acc: 0.9001
Epoch 628/1000
10001/10001 [==============================] - 0s 14us/step - loss: 0.2478 - acc: 0.9026
Epoch 629/1000
10001/10001 [==============================] - 0s 13us/step - loss: 0.2550 - acc: 0.8971
Epoch 630/1000
10001/10001 [==============================] - 0s 13us/step - loss: 0.2525 - acc: 0.8982
Epoch 631/1000
10001/10001 [==============================] - 0s 14us/step - loss: 0.2451 - acc: 0.9011
Epoch 632/1000
10001/10001 [==============================] - 0s 13us/step - loss: 0.2446 - acc: 0.9001
Epoch 633/1000
10001/10001 [==============================] - 0s 14us/step - loss: 0.2385 - acc: 0.9008
Epoch 634/1000
10001/10001 [==============================] - 0s 12us/step - loss: 0.2403 - acc: 0.8995
Epoch 635/1000
10001/10001 [==============================] - 0s 13us/step - lo

10001/10001 [==============================] - 0s 13us/step - loss: 0.2336 - acc: 0.9039
Epoch 705/1000
10001/10001 [==============================] - 0s 13us/step - loss: 0.2366 - acc: 0.9025
Epoch 706/1000
10001/10001 [==============================] - 0s 15us/step - loss: 0.2370 - acc: 0.9022
Epoch 707/1000
10001/10001 [==============================] - 0s 14us/step - loss: 0.2386 - acc: 0.9047
Epoch 708/1000
10001/10001 [==============================] - 0s 13us/step - loss: 0.2372 - acc: 0.9051
Epoch 709/1000
10001/10001 [==============================] - 0s 13us/step - loss: 0.2399 - acc: 0.9039
Epoch 710/1000
10001/10001 [==============================] - 0s 13us/step - loss: 0.2375 - acc: 0.9009
Epoch 711/1000
10001/10001 [==============================] - 0s 15us/step - loss: 0.2366 - acc: 0.9041
Epoch 712/1000
10001/10001 [==============================] - 0s 14us/step - loss: 0.2467 - acc: 0.8934
Epoch 713/1000
10001/10001 [==============================] - 0s 16us/step - lo

10001/10001 [==============================] - 0s 15us/step - loss: 0.2388 - acc: 0.9011
Epoch 783/1000
10001/10001 [==============================] - 0s 11us/step - loss: 0.2367 - acc: 0.9029
Epoch 784/1000
10001/10001 [==============================] - 0s 12us/step - loss: 0.2397 - acc: 0.9013
Epoch 785/1000
10001/10001 [==============================] - 0s 14us/step - loss: 0.2392 - acc: 0.9014
Epoch 786/1000
10001/10001 [==============================] - 0s 13us/step - loss: 0.2352 - acc: 0.9017
Epoch 787/1000
10001/10001 [==============================] - 0s 12us/step - loss: 0.2378 - acc: 0.9030
Epoch 788/1000
10001/10001 [==============================] - 0s 14us/step - loss: 0.2377 - acc: 0.9008
Epoch 789/1000
10001/10001 [==============================] - 0s 13us/step - loss: 0.2360 - acc: 0.9013
Epoch 790/1000
10001/10001 [==============================] - 0s 12us/step - loss: 0.2368 - acc: 0.9033
Epoch 791/1000
10001/10001 [==============================] - 0s 14us/step - lo

10001/10001 [==============================] - 0s 17us/step - loss: 0.2409 - acc: 0.9033
Epoch 861/1000
10001/10001 [==============================] - 0s 21us/step - loss: 0.2374 - acc: 0.9014
Epoch 862/1000
10001/10001 [==============================] - 0s 21us/step - loss: 0.2390 - acc: 0.9017
Epoch 863/1000
10001/10001 [==============================] - 0s 19us/step - loss: 0.2403 - acc: 0.9017
Epoch 864/1000
10001/10001 [==============================] - 0s 16us/step - loss: 0.2379 - acc: 0.9024
Epoch 865/1000
10001/10001 [==============================] - 0s 19us/step - loss: 0.2399 - acc: 0.9013
Epoch 866/1000
10001/10001 [==============================] - 0s 20us/step - loss: 0.2310 - acc: 0.9066: 0s - loss: 0.2302 - acc: 0.907
Epoch 867/1000
10001/10001 [==============================] - 0s 20us/step - loss: 0.2345 - acc: 0.9040
Epoch 868/1000
10001/10001 [==============================] - 0s 20us/step - loss: 0.2392 - acc: 0.9015
Epoch 869/1000
10001/10001 [===================

10001/10001 [==============================] - 0s 15us/step - loss: 0.2449 - acc: 0.8972
Epoch 939/1000
10001/10001 [==============================] - 0s 15us/step - loss: 0.2480 - acc: 0.9011
Epoch 940/1000
10001/10001 [==============================] - 0s 14us/step - loss: 0.2488 - acc: 0.8968
Epoch 941/1000
10001/10001 [==============================] - 0s 14us/step - loss: 0.2482 - acc: 0.8969
Epoch 942/1000
10001/10001 [==============================] - 0s 14us/step - loss: 0.2391 - acc: 0.8986
Epoch 943/1000
10001/10001 [==============================] - 0s 15us/step - loss: 0.2456 - acc: 0.8984
Epoch 944/1000
10001/10001 [==============================] - 0s 22us/step - loss: 0.2379 - acc: 0.9009
Epoch 945/1000
10001/10001 [==============================] - 0s 17us/step - loss: 0.2430 - acc: 0.9021
Epoch 946/1000
10001/10001 [==============================] - 0s 16us/step - loss: 0.2516 - acc: 0.8976
Epoch 947/1000
10001/10001 [==============================] - 0s 17us/step - lo

### Testing

In [38]:
test_data = pd.read_csv("tidy_dataset_test.csv")

In [39]:
x_test = test_data[test_data.columns[1:21]].values

In [40]:
x_test.shape

(298, 20)

In [41]:
y_test = test_data[test_data.columns[35]].values

In [42]:
y_test_final = np.zeros(shape=(y_test.shape[0] ,6))

In [43]:
for item in range(0, y_test.shape[0]):
    y_test_final[item][int(y_test[item])-1] = 0.99
  

In [44]:
classes = model.predict(x_test, batch_size=128)

In [45]:
model.predict

<bound method Sequential.predict of <keras.models.Sequential object at 0x000001DB6C96F710>>

In [46]:
classes.shape

(298, 6)

In [49]:
score = model.evaluate(x_test, y_test_final, batch_size=128)

298/298 [==============================] - 0s 107us/step


In [50]:
score

[0.19338867058289932, 0.9194630880483845]

In [51]:
print("Das Modell sagt die Testdaten zu: " + str(score[1]) + " Prozent richtig vorher.")
print("Es wurde mit " + str(y_train_preset.shape[0]) + " Datensätzen trainiert.")
print("Getestet wurde es mit bisher " + str(y_test.shape[0]) + " Datensätzen.")

Das Modell sagt die Testdaten zu: 0.919463088048 Prozent richtig vorher.
Es wurde mit 10001 Datensätzen trainiert.
Getestet wurde es mit bisher 298 Datensätzen.


In [52]:
model.save("without_fouier_try.h5")

In [2]:
model.load("first_try.h5")

NameError: name 'model' is not defined