In [86]:
from keras.models import Sequential
from keras.layers import Dense, Activation, Dropout
import numpy as np
import pandas as pd

https://keras.io/getting-started/sequential-model-guide/ 

## Shuffeln um bessere Ergebnisse zu erzielen

In [2]:
tidy = pd.read_csv('tidy_dataset.csv')

In [3]:
tidy = tidy.sample(frac=1).reset_index(drop=True)

In [4]:
tidy.shape

(10299, 35)

In [5]:
labelsDict = {
    'WALKING': 1,
    'WALKING_UPSTAIRS': 2,
    'WALKING_DOWNSTAIRS': 3,
    'SITTING': 4,
    'STANDING': 5,
    'LAYING': 6
}

In [6]:
tidy.to_csv(path_or_buf="tidy_dataset_all.csv")

In [7]:
df = pd.read_csv('tidy_dataset_training.csv')

In [8]:
df.head()

Unnamed: 0  tbodyaccmeanx  tbodyaccmeany  tbodyaccmeanz  tgravityaccmeanx  \
0           0       0.329943       0.017637       0.011913          0.831881   
1           1       0.331972      -0.007308      -0.110539          0.961025   
2           2       0.295423       0.003096      -0.127563          0.917727   
3           3       0.393122      -0.007415      -0.012344          0.944091   
4           4       0.319131      -0.008362      -0.113999          0.947141   

   tgravityaccmeany  tgravityaccmeanz  tbodyaccjerkmeanx  tbodyaccjerkmeany  \
0         -0.439108         -0.154553          -0.158938           0.133241   
1          0.056595          0.058772          -0.238494          -0.120963   
2         -0.305044         -0.106862           0.042129           0.036150   
3         -0.113783          0.108030          -0.011614          -0.163172   
4         -0.219883         -0.146451           0.260639          -0.167597   

   tbodyaccjerkmeanz    ...     fbodyaccjerkmeanz  fbodygyromeanx  \
0           0.027831    ...             -0.576268        0.021158   
1          -0.113624    ...             -0.390560       -0.327703   
2           0.140766    ...             -0.508754       -0.380509   
3          -0.243706    ...             -0.767078       -0.301157   
4          -0.197442    ...             -0.671305       -0.583020   

   fbodygyromeany  fbodygyromeanz  fbodyaccmagmean  fbodybodyaccjerkmagmean  \
0       -0.286196       -0.068256        -0.016640                -0.202842   
1       -0.301334       -0.110165        -0.037761                 0.108808   
2       -0.208828       -0.280720        -0.218158                -0.193487   
3       -0.676213       -0.486247        -0.425524                -0.563987   
4       -0.668782       -0.554829        -0.453847                -0.535373   

   fbodybodygyromagmean  fbodybodygyrojerkmagmean  subject  activity  
0             -0.308473                 -0.554294       19         2  
1             -0.333391                 -0.550982       10         1  
2             -0.209536                 -0.366694        1         1  
3             -0.479884                 -0.729436       25         3  
4             -0.698936                 -0.810464       27         2  

[5 rows x 36 columns]

Input shape ist (rows, columns)

In [9]:
x_train = df[df.columns[1:33]].values

In [10]:
y_train_preset = df[df.columns[35]].values

In [11]:
y_train_preset

array([2, 1, 1, ..., 4, 4, 3], dtype=int64)

In [12]:
y_train_final = np.zeros(shape=(y_train_preset.shape[0] ,6))

In [13]:
y_train_final[1]

array([ 0.,  0.,  0.,  0.,  0.,  0.])

In [14]:
for item in range(0, y_train_preset.shape[0]):
    y_train_final[item][int(y_train_preset[item])-1] = 0.99
    print(y_train_final[item])
    print(y_train_preset[item])

[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.    0.99]
6


[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.99  0.    0.    0.    0.  ]
2


6
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.    0.99]


[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.99  0.    0.  ]
4


[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.    0.99]
6


[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.99  0.    0.    0.  ]
3


[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.99  0.  ]
5


4
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.99  0.    0.    0.    0.  ]


[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.99  0.    0.  ]
4


[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.99  0.    0.  ]
4


3
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.99  0.  ]


[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.    0.99]
6


[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.    0.99]
6


[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.99  0.    0.    0.    0.  ]
2


5
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.    0.99]


[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.    0.99]
6


[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.99  0.  ]
5


[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.99  0.  ]
5


4
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.    0.99]


2
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.99  0.  ]


[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.99  0.    0.    0.    0.    0.  ]
1


[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.99  0.  ]
5


5
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.99  0.    0.    0.    0.  ]


6
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.99  0.    0.  ]


[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.99  0.  ]
5


[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.99  0.    0.    0.  ]
3


### Test Data

### Netz programmieren
Input ist jetzt vorbereitet

In [103]:
model = Sequential()
model.add(Dense(20, activation='relu', input_dim=32))
model.add(Dropout(0.2))
model.add(Dense(10, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(6, activation='softmax'))

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])



In [115]:
model.fit(x_train, y_train_final, epochs=400, batch_size=150)

Epoch 1/400
10001/10001 [==============================] - 0s 16us/step - loss: 0.1985 - acc: 0.9216
Epoch 2/400
10001/10001 [==============================] - 0s 14us/step - loss: 0.1940 - acc: 0.9232
Epoch 3/400
10001/10001 [==============================] - ETA: 0s - loss: 0.1964 - acc: 0.923 - 0s 15us/step - loss: 0.1935 - acc: 0.9248
Epoch 4/400
10001/10001 [==============================] - 0s 14us/step - loss: 0.1960 - acc: 0.9191
Epoch 5/400
10001/10001 [==============================] - 0s 14us/step - loss: 0.1925 - acc: 0.9227
Epoch 6/400
10001/10001 [==============================] - 0s 15us/step - loss: 0.1971 - acc: 0.9205
Epoch 7/400
10001/10001 [==============================] - 0s 15us/step - loss: 0.1925 - acc: 0.9213
Epoch 8/400
10001/10001 [==============================] - 0s 15us/step - loss: 0.1860 - acc: 0.9231
Epoch 9/400
10001/10001 [==============================] - 0s 15us/step - loss: 0.2049 - acc: 0.9181
Epoch 10/400
10001/10001 [===========================

10001/10001 [==============================] - 0s 15us/step - loss: 0.1950 - acc: 0.9156
Epoch 82/400
10001/10001 [==============================] - 0s 15us/step - loss: 0.1917 - acc: 0.9202
Epoch 83/400
10001/10001 [==============================] - 0s 14us/step - loss: 0.1982 - acc: 0.9182
Epoch 84/400
10001/10001 [==============================] - 0s 15us/step - loss: 0.1926 - acc: 0.9194
Epoch 85/400
10001/10001 [==============================] - 0s 18us/step - loss: 0.1954 - acc: 0.9178
Epoch 86/400
10001/10001 [==============================] - 0s 15us/step - loss: 0.1951 - acc: 0.9216
Epoch 87/400
10001/10001 [==============================] - 0s 17us/step - loss: 0.1906 - acc: 0.9192
Epoch 88/400
10001/10001 [==============================] - 0s 16us/step - loss: 0.1918 - acc: 0.9203
Epoch 89/400
10001/10001 [==============================] - 0s 17us/step - loss: 0.1893 - acc: 0.9258
Epoch 90/400
10001/10001 [==============================] - 0s 15us/step - loss: 0.1954 - acc: 

10001/10001 [==============================] - 0s 14us/step - loss: 0.1853 - acc: 0.9255
Epoch 161/400
10001/10001 [==============================] - 0s 13us/step - loss: 0.1875 - acc: 0.9209
Epoch 162/400
10001/10001 [==============================] - 0s 13us/step - loss: 0.1925 - acc: 0.9219
Epoch 163/400
10001/10001 [==============================] - 0s 13us/step - loss: 0.1889 - acc: 0.9210
Epoch 164/400
10001/10001 [==============================] - 0s 13us/step - loss: 0.1882 - acc: 0.9227
Epoch 165/400
10001/10001 [==============================] - 0s 13us/step - loss: 0.1883 - acc: 0.9240
Epoch 166/400
10001/10001 [==============================] - 0s 13us/step - loss: 0.1940 - acc: 0.9204
Epoch 167/400
10001/10001 [==============================] - 0s 13us/step - loss: 0.1874 - acc: 0.9226
Epoch 168/400
10001/10001 [==============================] - 0s 14us/step - loss: 0.1980 - acc: 0.9192
Epoch 169/400
10001/10001 [==============================] - 0s 13us/step - loss: 0.187

10001/10001 [==============================] - 0s 15us/step - loss: 0.1889 - acc: 0.9214
Epoch 240/400
10001/10001 [==============================] - 0s 15us/step - loss: 0.1912 - acc: 0.9214
Epoch 241/400
10001/10001 [==============================] - 0s 15us/step - loss: 0.1811 - acc: 0.9246
Epoch 242/400
10001/10001 [==============================] - 0s 15us/step - loss: 0.1880 - acc: 0.9182
Epoch 243/400
10001/10001 [==============================] - 0s 15us/step - loss: 0.1972 - acc: 0.9186
Epoch 244/400
10001/10001 [==============================] - 0s 13us/step - loss: 0.1884 - acc: 0.9198
Epoch 245/400
10001/10001 [==============================] - 0s 13us/step - loss: 0.1887 - acc: 0.9233
Epoch 246/400
10001/10001 [==============================] - 0s 13us/step - loss: 0.1908 - acc: 0.9221
Epoch 247/400
10001/10001 [==============================] - 0s 13us/step - loss: 0.1849 - acc: 0.9239
Epoch 248/400
10001/10001 [==============================] - 0s 13us/step - loss: 0.196

10001/10001 [==============================] - 0s 15us/step - loss: 0.1887 - acc: 0.9247
Epoch 319/400
10001/10001 [==============================] - 0s 14us/step - loss: 0.1901 - acc: 0.9215
Epoch 320/400
10001/10001 [==============================] - 0s 13us/step - loss: 0.1760 - acc: 0.9267
Epoch 321/400
10001/10001 [==============================] - 0s 13us/step - loss: 0.1887 - acc: 0.9225
Epoch 322/400
10001/10001 [==============================] - 0s 13us/step - loss: 0.1888 - acc: 0.9220
Epoch 323/400
10001/10001 [==============================] - 0s 14us/step - loss: 0.1956 - acc: 0.9197
Epoch 324/400
10001/10001 [==============================] - 0s 14us/step - loss: 0.1864 - acc: 0.9206
Epoch 325/400
10001/10001 [==============================] - 0s 13us/step - loss: 0.1858 - acc: 0.9219
Epoch 326/400
10001/10001 [==============================] - 0s 14us/step - loss: 0.1916 - acc: 0.9201
Epoch 327/400
10001/10001 [==============================] - 0s 13us/step - loss: 0.195

10001/10001 [==============================] - 0s 14us/step - loss: 0.1850 - acc: 0.9209
Epoch 398/400
10001/10001 [==============================] - 0s 13us/step - loss: 0.1883 - acc: 0.9221
Epoch 399/400
10001/10001 [==============================] - 0s 14us/step - loss: 0.1981 - acc: 0.9175
Epoch 400/400
10001/10001 [==============================] - 0s 13us/step - loss: 0.1835 - acc: 0.9242


### Testing

In [91]:
test_data = pd.read_csv("tidy_dataset_test.csv")

In [92]:
x_test = test_data[test_data.columns[1:33]].values

In [93]:
y_test = test_data[test_data.columns[35]].values

In [94]:
y_test_final = np.zeros(shape=(y_test.shape[0] ,6))

In [96]:
for item in range(0, y_test.shape[0]):
    y_test_final[item][int(y_test[item])-1] = 0.99
  

In [111]:
classes = model.predict(x_test, batch_size=128)

In [112]:
classes.shape

(298, 6)

In [116]:
score = model.evaluate(x_test, y_test_final, batch_size=128)

298/298 [==============================] - 0s 20us/step


In [117]:
score

[0.1028033796722857, 0.95973153962384938]

In [118]:
print("Das Modell sagt die Testdaten zu: " + str(score[1]) + " Prozent richtig vorher.")
print("Es wurde mit " + str(y_train_preset.shape[0]) + " Datensätzen trainiert.")
print("Getestet wurde es mit bisher " + str(y_test.shape[0]) + " Datensätzen.")

Das Modell sagt die Testdaten zu: 0.959731539624 Prozent richtig vorher.
Es wurde mit 10001 Datensätzen trainiert.
Getestet wurde es mit bisher 298 Datensätzen.


In [119]:
model.save("first_try.h5")