In [1]:
from keras.models import Sequential
from keras.layers import Dense, Activation, Dropout
import numpy as np
import pandas as pd

Using TensorFlow backend.


In [2]:
df = pd.read_csv('tidy_dataset_training.csv')

In [3]:
labelsDict = {
    'WALKING': 1,
    'WALKING_UPSTAIRS': 2,
    'WALKING_DOWNSTAIRS': 3,
    'SITTING': 4,
    'STANDING': 5,
    'LAYING': 6
}

In [4]:
x_train = df[df.columns[1:7]].values

In [5]:
x_train.shape

(10001, 6)

In [6]:
y_train_preset = df[df.columns[35]].values

In [7]:
y_train = np.zeros(shape=(y_train_preset.shape[0],6))

In [8]:
y_train[1]

array([ 0.,  0.,  0.,  0.,  0.,  0.])

In [9]:
for i, activity in enumerate(y_train_preset):
    y_train[i][activity-1] = 0.99
    print(y_train[i])
    print(y_train_preset[i])

[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.    0.99]
6


2
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.    0.99]


[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.99  0.    0.    0.    0.  ]
2


1
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.    0.99]


[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.99  0.    0.    0.  ]
3


[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.99  0.  ]
5


2
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.99  0.    0.    0.    0.  ]


5
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.99  0.    0.    0.    0.    0.  ]


5
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.99  0.  ]


[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.    0.99]
6


2
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.99  0.    0.    0.    0.  ]


1
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.99  0.    0.  ]


[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.99  0.  ]
5


[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.    0.99]
6


[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.99  0.    0.    0.    0.    0.  ]
1


2
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.99  0.  ]


[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.99  0.    0.    0.    0.    0.  ]
1


[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.    0.99]
6


[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.99  0.    0.    0.  ]
3


3
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.99  0.  ]


[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.99  0.    0.    0.  ]
3


[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.99  0.    0.    0.    0.    0.  ]
1


[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.99  0.    0.  ]
4


4
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.99  0.    0.    0.    0.  ]


6
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.99  0.    0.    0.    0.  ]


[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.99  0.    0.    0.    0.  ]
2


[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.99  0.    0.    0.  ]
3
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.99  0.    0.    0.    0.  ]
2
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.99  0.    0.    0.    0.    0.  ]
1
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.99  0.  ]
5
[ 0.    0.    0.    0.99  0.    0.  ]
4
[ 0.    0.    0.    0.    0.    0.99]
6
[ 0.    0.    0.    0.    0.    0.99]
6


In [10]:
model = Sequential()
model.add(Dense(20, activation='relu', input_dim=(6)))
model.add(Dropout(0.1))
model.add(Dense(20, activation='relu'))
model.add(Dropout(0.1))
model.add(Dense(6, activation='softmax'))

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])



In [11]:
test_data = pd.read_csv("tidy_dataset_test.csv")
x_test = test_data[test_data.columns[1:7]].values
y_test = test_data[test_data.columns[35]].values
y_test_final = np.zeros(shape=(y_test.shape[0] ,6))
for item in range(0, y_test.shape[0]):
    y_test_final[item][int(y_test[item])-1] = 0.99
  

In [17]:
modelAccuracy = {}
def fitAndEvaluateModel(epochs,batch_size):
    model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
    model.fit(x_train, y_train, epochs=epochs, batch_size=batch_size)
    score = model.evaluate(x_test, y_test_final, batch_size=batch_size)
    
    modelAccuracy["Epochen: " + str(epochs) + "| Batchsize: " + str(batch_size)] = score

In [18]:
modelAccuracy

{}

In [21]:
for i in range(10, 410, 100):
    for j in range(10, 110, 60):
        fitAndEvaluateModel(i, j)

Epoch 1/10
10001/10001 [==============================] - 2s 154us/step - loss: 0.6291 - acc: 0.7449
Epoch 2/10
10001/10001 [==============================] - 1s 118us/step - loss: 0.6273 - acc: 0.7422
Epoch 3/10
10001/10001 [==============================] - 1s 118us/step - loss: 0.6331 - acc: 0.7430
Epoch 4/10
10001/10001 [==============================] - 1s 120us/step - loss: 0.6432 - acc: 0.7440
Epoch 5/10
10001/10001 [==============================] - 1s 120us/step - loss: 0.6300 - acc: 0.7471
Epoch 6/10
10001/10001 [==============================] - 1s 119us/step - loss: 0.6367 - acc: 0.7424
Epoch 7/10
10001/10001 [==============================] - 1s 121us/step - loss: 0.6368 - acc: 0.7424 1s - los
Epoch 8/10
10001/10001 [==============================] - 1s 118us/step - loss: 0.6274 - acc: 0.7482
Epoch 9/10
10001/10001 [==============================] - 1s 120us/step - loss: 0.6309 - acc: 0.7417 1s - los
Epoch 10/10
298/298 [==============================] - 0s 461us/step
Epoc

10001/10001 [==============================] - 1s 132us/step - loss: 0.6283 - acc: 0.7448
Epoch 60/110
10001/10001 [==============================] - 1s 131us/step - loss: 0.6329 - acc: 0.7474
Epoch 61/110
10001/10001 [==============================] - 1s 118us/step - loss: 0.6293 - acc: 0.7451
Epoch 62/110
10001/10001 [==============================] - 1s 116us/step - loss: 0.6369 - acc: 0.7423
Epoch 63/110
10001/10001 [==============================] - 1s 115us/step - loss: 0.6347 - acc: 0.7427
Epoch 64/110
10001/10001 [==============================] - 1s 116us/step - loss: 0.6404 - acc: 0.7433
Epoch 65/110
10001/10001 [==============================] - 1s 115us/step - loss: 0.6277 - acc: 0.7456
Epoch 66/110
10001/10001 [==============================] - 1s 116us/step - loss: 0.6227 - acc: 0.7482
Epoch 67/110
10001/10001 [==============================] - 1s 115us/step - loss: 0.6390 - acc: 0.7407
Epoch 68/110
10001/10001 [==============================] - 1s 116us/step - loss: 0.63

10001/10001 [==============================] - 0s 21us/step - loss: 0.6188 - acc: 0.7482
Epoch 29/110
10001/10001 [==============================] - 0s 20us/step - loss: 0.6088 - acc: 0.7540
Epoch 30/110
10001/10001 [==============================] - 0s 20us/step - loss: 0.6150 - acc: 0.7526
Epoch 31/110
10001/10001 [==============================] - 0s 20us/step - loss: 0.6209 - acc: 0.7493
Epoch 32/110
10001/10001 [==============================] - 0s 20us/step - loss: 0.6165 - acc: 0.7507
Epoch 33/110
10001/10001 [==============================] - 0s 21us/step - loss: 0.6229 - acc: 0.7539
Epoch 34/110
10001/10001 [==============================] - 0s 20us/step - loss: 0.6131 - acc: 0.7515
Epoch 35/110
10001/10001 [==============================] - 0s 20us/step - loss: 0.6163 - acc: 0.7500
Epoch 36/110
10001/10001 [==============================] - 0s 21us/step - loss: 0.6147 - acc: 0.7480
Epoch 37/110
10001/10001 [==============================] - 0s 20us/step - loss: 0.6150 - acc: 

10001/10001 [==============================] - 0s 21us/step - loss: 0.6180 - acc: 0.7473
Epoch 109/110
10001/10001 [==============================] - 0s 20us/step - loss: 0.6169 - acc: 0.7526
Epoch 110/110
298/298 [==============================] - 0s 410us/step
Epoch 1/210
10001/10001 [==============================] - 1s 147us/step - loss: 0.6270 - acc: 0.7424
Epoch 2/210
10001/10001 [==============================] - 1s 113us/step - loss: 0.6305 - acc: 0.7480
Epoch 3/210
10001/10001 [==============================] - 1s 127us/step - loss: 0.6292 - acc: 0.7467
Epoch 4/210
10001/10001 [==============================] - 1s 134us/step - loss: 0.6339 - acc: 0.7451
Epoch 5/210
10001/10001 [==============================] - 1s 129us/step - loss: 0.6347 - acc: 0.7370
Epoch 6/210
10001/10001 [==============================] - 1s 129us/step - loss: 0.6263 - acc: 0.7472
Epoch 7/210
10001/10001 [==============================] - 1s 121us/step - loss: 0.6313 - acc: 0.7457
Epoch 8/210
10001/10001

10001/10001 [==============================] - 1s 114us/step - loss: 0.6290 - acc: 0.7441
Epoch 78/210
10001/10001 [==============================] - 1s 112us/step - loss: 0.6292 - acc: 0.7489
Epoch 79/210
10001/10001 [==============================] - 1s 112us/step - loss: 0.6333 - acc: 0.7388
Epoch 80/210
10001/10001 [==============================] - 1s 118us/step - loss: 0.6356 - acc: 0.7441
Epoch 81/210
10001/10001 [==============================] - 1s 114us/step - loss: 0.6285 - acc: 0.7473
Epoch 82/210
10001/10001 [==============================] - 1s 120us/step - loss: 0.6308 - acc: 0.7421
Epoch 83/210
10001/10001 [==============================] - 1s 139us/step - loss: 0.6299 - acc: 0.7416
Epoch 84/210
10001/10001 [==============================] - 1s 128us/step - loss: 0.6308 - acc: 0.7474
Epoch 85/210
10001/10001 [==============================] - 1s 128us/step - loss: 0.6297 - acc: 0.7433
Epoch 86/210
10001/10001 [==============================] - 1s 124us/step - loss: 0.62

10001/10001 [==============================] - 1s 120us/step - loss: 0.6272 - acc: 0.7498
Epoch 157/210
10001/10001 [==============================] - 1s 141us/step - loss: 0.6348 - acc: 0.7404
Epoch 158/210
10001/10001 [==============================] - 1s 130us/step - loss: 0.6354 - acc: 0.7439
Epoch 159/210
10001/10001 [==============================] - 1s 129us/step - loss: 0.6279 - acc: 0.7449
Epoch 160/210
10001/10001 [==============================] - 1s 132us/step - loss: 0.6330 - acc: 0.7430
Epoch 161/210
10001/10001 [==============================] - 1s 116us/step - loss: 0.6297 - acc: 0.7388
Epoch 162/210
10001/10001 [==============================] - 1s 115us/step - loss: 0.6219 - acc: 0.7472
Epoch 163/210
10001/10001 [==============================] - 1s 115us/step - loss: 0.6344 - acc: 0.7432
Epoch 164/210
10001/10001 [==============================] - 1s 115us/step - loss: 0.6346 - acc: 0.7391
Epoch 165/210
10001/10001 [==============================] - 1s 116us/step - l

10001/10001 [==============================] - 0s 32us/step - loss: 0.6137 - acc: 0.7474
Epoch 24/210
10001/10001 [==============================] - 0s 33us/step - loss: 0.6167 - acc: 0.7503
Epoch 25/210
10001/10001 [==============================] - 0s 33us/step - loss: 0.6115 - acc: 0.7506
Epoch 26/210
10001/10001 [==============================] - 0s 33us/step - loss: 0.6199 - acc: 0.7491
Epoch 27/210
10001/10001 [==============================] - 0s 33us/step - loss: 0.6203 - acc: 0.7492
Epoch 28/210
10001/10001 [==============================] - 0s 34us/step - loss: 0.6180 - acc: 0.7498
Epoch 29/210
10001/10001 [==============================] - 0s 33us/step - loss: 0.6102 - acc: 0.7559
Epoch 30/210
10001/10001 [==============================] - 0s 32us/step - loss: 0.6133 - acc: 0.7528
Epoch 31/210
10001/10001 [==============================] - 0s 32us/step - loss: 0.6077 - acc: 0.7527
Epoch 32/210
10001/10001 [==============================] - 0s 33us/step - loss: 0.6086 - acc: 

10001/10001 [==============================] - 0s 37us/step - loss: 0.6107 - acc: 0.7500
Epoch 104/210
10001/10001 [==============================] - 0s 35us/step - loss: 0.6122 - acc: 0.7547
Epoch 105/210
10001/10001 [==============================] - 0s 38us/step - loss: 0.6209 - acc: 0.7427
Epoch 106/210
10001/10001 [==============================] - 0s 33us/step - loss: 0.6119 - acc: 0.7523
Epoch 107/210
10001/10001 [==============================] - 0s 35us/step - loss: 0.6083 - acc: 0.7524
Epoch 108/210
10001/10001 [==============================] - 0s 34us/step - loss: 0.6230 - acc: 0.7499
Epoch 109/210
10001/10001 [==============================] - 0s 34us/step - loss: 0.6140 - acc: 0.7559
Epoch 110/210
10001/10001 [==============================] - 0s 32us/step - loss: 0.6116 - acc: 0.7522
Epoch 111/210
10001/10001 [==============================] - 0s 35us/step - loss: 0.6160 - acc: 0.7492
Epoch 112/210
10001/10001 [==============================] - 0s 36us/step - loss: 0.615

10001/10001 [==============================] - 0s 35us/step - loss: 0.6178 - acc: 0.7515
Epoch 183/210
10001/10001 [==============================] - 0s 35us/step - loss: 0.6137 - acc: 0.7489
Epoch 184/210
10001/10001 [==============================] - 0s 35us/step - loss: 0.6156 - acc: 0.7495
Epoch 185/210
10001/10001 [==============================] - 0s 36us/step - loss: 0.6115 - acc: 0.7491
Epoch 186/210
10001/10001 [==============================] - 0s 36us/step - loss: 0.6107 - acc: 0.7514
Epoch 187/210
10001/10001 [==============================] - 0s 35us/step - loss: 0.6142 - acc: 0.7487
Epoch 188/210
10001/10001 [==============================] - 0s 35us/step - loss: 0.6117 - acc: 0.7533
Epoch 189/210
10001/10001 [==============================] - 0s 36us/step - loss: 0.6194 - acc: 0.7468
Epoch 190/210
10001/10001 [==============================] - 0s 35us/step - loss: 0.6162 - acc: 0.7506
Epoch 191/210
10001/10001 [==============================] - 0s 35us/step - loss: 0.613

10001/10001 [==============================] - 2s 211us/step - loss: 0.6357 - acc: 0.7449
Epoch 52/310
10001/10001 [==============================] - 2s 180us/step - loss: 0.6255 - acc: 0.7449
Epoch 53/310
10001/10001 [==============================] - 2s 185us/step - loss: 0.6372 - acc: 0.7468
Epoch 54/310
10001/10001 [==============================] - 2s 203us/step - loss: 0.6320 - acc: 0.7442
Epoch 55/310
10001/10001 [==============================] - 2s 200us/step - loss: 0.6245 - acc: 0.7480
Epoch 56/310
10001/10001 [==============================] - 2s 230us/step - loss: 0.6258 - acc: 0.7454
Epoch 57/310
10001/10001 [==============================] - 2s 210us/step - loss: 0.6292 - acc: 0.7447
Epoch 58/310
10001/10001 [==============================] - 2s 219us/step - loss: 0.6246 - acc: 0.7467
Epoch 59/310
10001/10001 [==============================] - 2s 220us/step - loss: 0.6205 - acc: 0.7512
Epoch 60/310
10001/10001 [==============================] - 2s 211us/step - loss: 0.63

10001/10001 [==============================] - 2s 231us/step - loss: 0.6228 - acc: 0.7468
Epoch 131/310
10001/10001 [==============================] - 2s 214us/step - loss: 0.6258 - acc: 0.7459
Epoch 132/310
10001/10001 [==============================] - 2s 213us/step - loss: 0.6250 - acc: 0.7392
Epoch 133/310
10001/10001 [==============================] - 2s 183us/step - loss: 0.6189 - acc: 0.7471
Epoch 134/310
10001/10001 [==============================] - 2s 199us/step - loss: 0.6369 - acc: 0.7438
Epoch 135/310
10001/10001 [==============================] - 2s 195us/step - loss: 0.6261 - acc: 0.7456
Epoch 136/310
10001/10001 [==============================] - 2s 193us/step - loss: 0.6233 - acc: 0.7483
Epoch 137/310
10001/10001 [==============================] - 2s 199us/step - loss: 0.6335 - acc: 0.7404
Epoch 138/310
10001/10001 [==============================] - 2s 237us/step - loss: 0.6333 - acc: 0.7445
Epoch 139/310
10001/10001 [==============================] - 2s 236us/step - l

10001/10001 [==============================] - 2s 209us/step - loss: 0.6198 - acc: 0.7499
Epoch 209/310
10001/10001 [==============================] - 2s 205us/step - loss: 0.6285 - acc: 0.7492
Epoch 210/310
10001/10001 [==============================] - 2s 206us/step - loss: 0.6293 - acc: 0.7456
Epoch 211/310
10001/10001 [==============================] - 2s 214us/step - loss: 0.6213 - acc: 0.7463
Epoch 212/310
10001/10001 [==============================] - 2s 233us/step - loss: 0.6291 - acc: 0.7439
Epoch 213/310
10001/10001 [==============================] - 2s 238us/step - loss: 0.6194 - acc: 0.7484
Epoch 214/310
10001/10001 [==============================] - 2s 231us/step - loss: 0.6247 - acc: 0.7477
Epoch 215/310
10001/10001 [==============================] - 2s 221us/step - loss: 0.6295 - acc: 0.7465
Epoch 216/310
10001/10001 [==============================] - 2s 199us/step - loss: 0.6248 - acc: 0.7450
Epoch 217/310
10001/10001 [==============================] - 2s 203us/step - l

10001/10001 [==============================] - 2s 214us/step - loss: 0.6226 - acc: 0.7504
Epoch 287/310
10001/10001 [==============================] - 2s 209us/step - loss: 0.6230 - acc: 0.7441
Epoch 288/310
10001/10001 [==============================] - 2s 213us/step - loss: 0.6273 - acc: 0.7472
Epoch 289/310
10001/10001 [==============================] - 2s 203us/step - loss: 0.6294 - acc: 0.7449
Epoch 290/310
10001/10001 [==============================] - 2s 196us/step - loss: 0.6248 - acc: 0.7451
Epoch 291/310
10001/10001 [==============================] - 2s 205us/step - loss: 0.6232 - acc: 0.7469
Epoch 292/310
10001/10001 [==============================] - 2s 213us/step - loss: 0.6180 - acc: 0.7527
Epoch 293/310
10001/10001 [==============================] - 2s 236us/step - loss: 0.6285 - acc: 0.7459
Epoch 294/310
10001/10001 [==============================] - 2s 219us/step - loss: 0.6237 - acc: 0.7478
Epoch 295/310
10001/10001 [==============================] - 2s 218us/step - l

10001/10001 [==============================] - 0s 36us/step - loss: 0.6100 - acc: 0.7548
Epoch 55/310
10001/10001 [==============================] - 0s 35us/step - loss: 0.6220 - acc: 0.7486
Epoch 56/310
10001/10001 [==============================] - 0s 37us/step - loss: 0.6131 - acc: 0.7503
Epoch 57/310
10001/10001 [==============================] - 0s 36us/step - loss: 0.6026 - acc: 0.7573
Epoch 58/310
10001/10001 [==============================] - 0s 39us/step - loss: 0.6090 - acc: 0.7515
Epoch 59/310
10001/10001 [==============================] - 0s 36us/step - loss: 0.6070 - acc: 0.7530
Epoch 60/310
10001/10001 [==============================] - 0s 33us/step - loss: 0.6133 - acc: 0.7540
Epoch 61/310
10001/10001 [==============================] - 0s 34us/step - loss: 0.6063 - acc: 0.7543
Epoch 62/310
10001/10001 [==============================] - 0s 34us/step - loss: 0.6135 - acc: 0.7495
Epoch 63/310
10001/10001 [==============================] - 0s 32us/step - loss: 0.6139 - acc: 

10001/10001 [==============================] - 0s 33us/step - loss: 0.6132 - acc: 0.7547
Epoch 135/310
10001/10001 [==============================] - 0s 34us/step - loss: 0.6177 - acc: 0.7483
Epoch 136/310
10001/10001 [==============================] - 0s 34us/step - loss: 0.6107 - acc: 0.7538: 0s - loss: 0.6145 - acc: 0.
Epoch 137/310
10001/10001 [==============================] - 0s 35us/step - loss: 0.6088 - acc: 0.7530
Epoch 138/310
10001/10001 [==============================] - 0s 35us/step - loss: 0.6088 - acc: 0.7523
Epoch 139/310
10001/10001 [==============================] - 0s 39us/step - loss: 0.6131 - acc: 0.7518
Epoch 140/310
10001/10001 [==============================] - 0s 35us/step - loss: 0.6199 - acc: 0.7491
Epoch 141/310
10001/10001 [==============================] - 0s 35us/step - loss: 0.6144 - acc: 0.7488
Epoch 142/310
10001/10001 [==============================] - 0s 36us/step - loss: 0.6138 - acc: 0.7517
Epoch 143/310
10001/10001 [==============================]

10001/10001 [==============================] - 0s 35us/step - loss: 0.6128 - acc: 0.7518
Epoch 214/310
10001/10001 [==============================] - 0s 37us/step - loss: 0.6101 - acc: 0.7521
Epoch 215/310
10001/10001 [==============================] - 0s 37us/step - loss: 0.6117 - acc: 0.7487
Epoch 216/310
10001/10001 [==============================] - 0s 39us/step - loss: 0.6093 - acc: 0.7551
Epoch 217/310
10001/10001 [==============================] - 0s 37us/step - loss: 0.6100 - acc: 0.7518
Epoch 218/310
10001/10001 [==============================] - 0s 35us/step - loss: 0.6085 - acc: 0.7526
Epoch 219/310
10001/10001 [==============================] - 0s 35us/step - loss: 0.6084 - acc: 0.7513
Epoch 220/310
10001/10001 [==============================] - 0s 35us/step - loss: 0.6000 - acc: 0.7559
Epoch 221/310
10001/10001 [==============================] - 0s 36us/step - loss: 0.6122 - acc: 0.7533
Epoch 222/310
10001/10001 [==============================] - 0s 37us/step - loss: 0.604

10001/10001 [==============================] - 0s 31us/step - loss: 0.6152 - acc: 0.7520
Epoch 293/310
10001/10001 [==============================] - 0s 33us/step - loss: 0.6145 - acc: 0.7509
Epoch 294/310
10001/10001 [==============================] - 0s 35us/step - loss: 0.6153 - acc: 0.7571
Epoch 295/310
10001/10001 [==============================] - 0s 34us/step - loss: 0.6137 - acc: 0.7522
Epoch 296/310
10001/10001 [==============================] - 0s 34us/step - loss: 0.6160 - acc: 0.7519
Epoch 297/310
10001/10001 [==============================] - 0s 35us/step - loss: 0.6102 - acc: 0.7561
Epoch 298/310
10001/10001 [==============================] - 0s 34us/step - loss: 0.6115 - acc: 0.7532
Epoch 299/310
10001/10001 [==============================] - 0s 34us/step - loss: 0.6152 - acc: 0.7494
Epoch 300/310
10001/10001 [==============================] - 0s 34us/step - loss: 0.6138 - acc: 0.7549
Epoch 301/310
10001/10001 [==============================] - 0s 38us/step - loss: 0.609

In [22]:
modelAccuracy


{'Epochen: 10| Batchsize: 10': [0.57386759163549284, 0.78523489372842259],
 'Epochen: 10| Batchsize: 100': [0.56296531426026519, 0.78187918663024902],
 'Epochen: 10| Batchsize: 40': [0.55369156999075975, 0.77516778163461875],
 'Epochen: 10| Batchsize: 70': [0.55021685621882443, 0.77852348913282354],
 'Epochen: 110| Batchsize: 10': [0.57196007308943964, 0.7718120845372245],
 'Epochen: 110| Batchsize: 70': [0.57117033724816857, 0.78523489812876557],
 'Epochen: 210| Batchsize: 10': [0.56651355196165554, 0.77852349073294824],
 'Epochen: 210| Batchsize: 70': [0.5484068491714913, 0.775167777634307],
 'Epochen: 310| Batchsize: 10': [0.54807607899576227, 0.78187919423084129],
 'Epochen: 310| Batchsize: 70': [0.53842685066613571, 0.77852348913282354]}